### PR TITLE
Add a filter flag in i3-container-commander.py

### PR DESCRIPTION
**Pull request by teto**
if you want to run it for a specific application:
i3-container-commander.py --filter qutebrowser

### CODE REVIEW

**Comment by acrisci** [comment]
`--filter` seems a bit ambiguous to me since there are potentially a few things that could be being filtered. Can you change it to `--filter-group` or something more specific?

**Comment by teto** [comment]
Updated it, I use the script with rofi rather than with dmenu but I guess it would be easier for me to generate a rofi wrapper called "dmenu" :)

**Comment by acrisci** [comment]
You can either create a symlink in your path with basename dmenu or use the new flag `--menu rofi` to make this work with rofi.

**Comment by teto** [comment]
I've started using sway. Closing

**Pull request closed without merging**
